language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# deploy 명령어가 실행되기 전 수행
before_deploy:
  - zip -r bedi-webservice ./*
  - mkdir -p deploy
  - mv bedi-webservice.zip deploy/bedi-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: bedi
    region: ap-northeast-2
    cleanup: false
    acl: private
    local_dir: deploy
    edge: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: bedi
    key: bedi-webservice.zip
    bundle_type: zip
    application: bedi-webservice

    deployment_group: bedi-webservice-group
    region: ap-northeast-2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - mby1997s@gmail.com
